export const UPDATE_DATA = 'UPDATE_DATA'
export const UPDATE_TEST_DATA = "UPDATE_TEST_DATA"
export const STORING_DATA = "STORING_DATA"
export const CLEAR_STORING_DATA = "CLEAR_STORING_DATA"
export const CLEAR_DATA = "CLEAR_DATA"